export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const STOP_AUTH_LOADING = 'STOP_AUTH_LOADING';

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION';
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const SET_TRANSACTION = 'SET_TRANSACTION';
export const TRANSACTIONS_LOADING = 'TRANSACTIONS_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';
export const SORT_BY_DATE = 'SORT_BY_DATE';
export const SORT_BY_AMOUNT = 'SORT_BY_AMOUNT';
export const SORT_BY_TYPE = 'SORT_BY_TYPE';
export const SET_START_DATE = 'SET_START_DATE';
export const SET_END_DATE = 'SET_END_DATE';
